2023-09-08 13:28:30,185 ERROR root ScriptRunner.scriptThread api_client.py make_api_call : Error making API call: HTTPConnectionPool(host='10.0.1.3', port=8080): Max retries exceeded with url: /preprocessing/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f720306a670>: Failed to establish a new connection: [Errno 111] Connection refused'))
